export const conversationUpdated = {
  'payload': {
    'conversation_updated': {
      'conversation': {
        'applies_to_parts': [{
          'display_id': 'CAPL-515',
          'id': 'don:core:dvrv-us-1:devo/787:capability/515',
          'id_v1': 'don:DEV-787:capability:515',
          'name': 'Customer Product Discovery',
          'type': 'capability',
        }],
        'broadcast_channels': ['chat'],
        'created_by': {
          'display_handle': 'sunil-pandey',
          'display_id': 'REVU-16',
          'display_name': 'sunil-pandey',
          'email': 'sunil.pandey@devrev.ai',
          'external_ref': 'don:identity:dvrv-us-1:devo/787:devu/11',
          'id': 'don:identity:dvrv-us-1:devo/787:revo/35:revu/16',
          'id_v1': 'don:DEV-787:rev_user:REV-35/REVU-16',
          'rev_org': {
            'display_id': 'REV-35',
            'display_name': 'DevRev',
            'id': 'don:identity:dvrv-us-1:devo/787:revo/35',
            'id_v1': 'don:DEV-787:rev_org:REV-35',
            'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/DevRev.svg',
            'type': 'rev_org',
          },
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/sunil-pandey.svg',
          'type': 'rev_user',
        },
        'created_date': '2023-04-19T16:37:51.251Z',
        'display_id': 'CONV-3176',
        'id': 'don:core:dvrv-us-1:devo/787:conversation/3176',
        'id_v1': 'don:DEV-787:conversation:3176',
        'members': [{
          'display_handle': 'sunil-pandey',
          'display_id': 'REVU-16',
          'display_name': 'sunil-pandey',
          'email': 'sunil.pandey@devrev.ai',
          'external_ref': 'don:identity:dvrv-us-1:devo/787:devu/11',
          'id': 'don:identity:dvrv-us-1:devo/787:revo/35:revu/16',
          'id_v1': 'don:DEV-787:rev_user:REV-35/REVU-16',
          'rev_org': {
            'display_id': 'REV-35',
            'display_name': 'DevRev',
            'id': 'don:identity:dvrv-us-1:devo/787:revo/35',
            'id_v1': 'don:DEV-787:rev_org:REV-35',
            'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/DevRev.svg',
            'type': 'rev_org',
          },
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/sunil-pandey.svg',
          'type': 'rev_user',
        }, {
          'display_handle': 'i-aman-mahajan',
          'display_id': 'DEVU-298',
          'display_name': 'i-aman-mahajan',
          'email': 'i-aman.mahajan@devrev.ai',
          'full_name': 'Aman Mahajan',
          'id': 'don:identity:dvrv-us-1:devo/787:devu/298',
          'id_v1': 'don:DEV-787:dev_user:DEVU-298',
          'state': 'active',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/Aman%20Mahajan.svg',
          'type': 'dev_user',
        }],
        'modified_by': {
          'display_handle': 'amit-gosavi',
          'display_id': 'DEVU-170',
          'display_name': 'amit-gosavi',
          'email': 'amit.gosavi@devrev.ai',
          'full_name': 'Amit Gosavi',
          'id': 'don:identity:dvrv-us-1:devo/787:devu/170',
          'id_v1': 'don:DEV-787:dev_user:DEVU-170',
          'state': 'active',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/Amit%20Gosavi.svg',
          'type': 'dev_user',
        },
        'modified_date': '2023-05-15T16:39:10.711Z',
        'owned_by': [{
          'display_handle': 'shashank-singh',
          'display_id': 'DEVU-215',
          'display_name': 'shashank-singh',
          'email': 'shashank.singh@devrev.ai',
          'full_name': 'Shashank Singh',
          'id': 'don:identity:dvrv-us-1:devo/787:devu/215',
          'id_v1': 'don:DEV-787:dev_user:DEVU-215',
          'state': 'active',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/Shashank%20Singh.svg',
          'type': 'dev_user',
        }],
        'rev_orgs': [{
          'display_id': 'REV-35',
          'display_name': 'DevRev',
          'id': 'don:identity:dvrv-us-1:devo/787:revo/35',
          'id_v1': 'don:DEV-787:rev_org:REV-35',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/DevRev.svg',
          'type': 'rev_org',
        }],
        'sla_summary': {
          'closest_to_breach_metric': 'First response',
          'sla_tracker': {
            'display_id': 'sla_tracker-1',
            'id': 'don:core:dvrv-us-1:devo/787:conversation/3176:sla_tracker/1',
            'metric_target_summaries': [{
              'is_out_of_schedule': false,
              'metric_definition': {
                'id': 'don:core:dvrv-us-1:devo/787:metric_definition/1',
                'metric_type': 'time',
                'name': 'First response',
              },
              'stage': 'completed',
            }],
            'sla': {
              'display_id': 'sla-35',
              'id': 'don:core:dvrv-us-1:devo/787:sla/35',
              'name': 'Demo SLA with tickets',
              'status': 'published',
            },
            'sla_policy_id': 'don:core:dvrv-us-1:devo/787:sla/35:sla_policy/0',
            'stage': 'completed',
          },
          'stage': 'completed',
          'target_time': '2023-04-19T16:47:51.251Z',
        },
        'source_channel': 'chat',
        'stage': {
          'name': 'resolved',
          'ordinal': 6000,
        },
        'state': 'closed',
        'status': 'closed',
        'title': '',
      },
      'old_conversation': {
        'applies_to_parts': [{
          'display_id': 'CAPL-515',
          'id': 'don:core:dvrv-us-1:devo/787:capability/515',
          'id_v1': 'don:DEV-787:capability:515',
          'name': 'Customer Product Discovery',
          'type': 'capability',
        }],
        'broadcast_channels': ['chat'],
        'created_by': {
          'display_handle': 'sunil-pandey',
          'display_id': 'REVU-16',
          'display_name': 'sunil-pandey',
          'email': 'sunil.pandey@devrev.ai',
          'external_ref': 'don:identity:dvrv-us-1:devo/787:devu/11',
          'id': 'don:identity:dvrv-us-1:devo/787:revo/35:revu/16',
          'id_v1': 'don:DEV-787:rev_user:REV-35/REVU-16',
          'rev_org': {
            'display_id': 'REV-35',
            'display_name': 'DevRev',
            'id': 'don:identity:dvrv-us-1:devo/787:revo/35',
            'id_v1': 'don:DEV-787:rev_org:REV-35',
            'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/DevRev.svg',
            'type': 'rev_org',
          },
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/sunil-pandey.svg',
          'type': 'rev_user',
        },
        'created_date': '2023-04-19T16:37:51.251Z',
        'display_id': 'CONV-3176',
        'id': 'don:core:dvrv-us-1:devo/787:conversation/3176',
        'id_v1': 'don:DEV-787:conversation:3176',
        'members': [{
          'display_handle': 'sunil-pandey',
          'display_id': 'REVU-16',
          'display_name': 'sunil-pandey',
          'email': 'sunil.pandey@devrev.ai',
          'external_ref': 'don:identity:dvrv-us-1:devo/787:devu/11',
          'id': 'don:identity:dvrv-us-1:devo/787:revo/35:revu/16',
          'id_v1': 'don:DEV-787:rev_user:REV-35/REVU-16',
          'rev_org': {
            'display_id': 'REV-35',
            'display_name': 'DevRev',
            'id': 'don:identity:dvrv-us-1:devo/787:revo/35',
            'id_v1': 'don:DEV-787:rev_org:REV-35',
            'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/DevRev.svg',
            'type': 'rev_org',
          },
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/sunil-pandey.svg',
          'type': 'rev_user',
        }, {
          'display_handle': 'i-aman-mahajan',
          'display_id': 'DEVU-298',
          'display_name': 'i-aman-mahajan',
          'email': 'i-aman.mahajan@devrev.ai',
          'full_name': 'Aman Mahajan',
          'id': 'don:identity:dvrv-us-1:devo/787:devu/298',
          'id_v1': 'don:DEV-787:dev_user:DEVU-298',
          'state': 'active',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/Aman%20Mahajan.svg',
          'type': 'dev_user',
        }],
        'modified_by': {
          'display_handle': 'amit-gosavi',
          'display_id': 'DEVU-170',
          'display_name': 'amit-gosavi',
          'email': 'amit.gosavi@devrev.ai',
          'full_name': 'Amit Gosavi',
          'id': 'don:identity:dvrv-us-1:devo/787:devu/170',
          'id_v1': 'don:DEV-787:dev_user:DEVU-170',
          'state': 'active',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/Amit%20Gosavi.svg',
          'type': 'dev_user',
        },
        'modified_date': '2023-05-15T16:39:05.452Z',
        'owned_by': [{
          'display_handle': 'shashank-singh',
          'display_id': 'DEVU-215',
          'display_name': 'shashank-singh',
          'email': 'shashank.singh@devrev.ai',
          'full_name': 'Shashank Singh',
          'id': 'don:identity:dvrv-us-1:devo/787:devu/215',
          'id_v1': 'don:DEV-787:dev_user:DEVU-215',
          'state': 'active',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/Shashank%20Singh.svg',
          'type': 'dev_user',
        }],
        'rev_orgs': [{
          'display_id': 'REV-35',
          'display_name': 'DevRev',
          'id': 'don:identity:dvrv-us-1:devo/787:revo/35',
          'id_v1': 'don:DEV-787:rev_org:REV-35',
          'thumbnail': 'https://api.dev.devrev-eng.ai/internal/display-picture/DevRev.svg',
          'type': 'rev_org',
        }],
        'sla_summary': {
          'closest_to_breach_metric': 'First response',
          'sla_tracker': {
            'display_id': 'sla_tracker-1',
            'id': 'don:core:dvrv-us-1:devo/787:conversation/3176:sla_tracker/1',
            'metric_target_summaries': [{
              'is_out_of_schedule': false,
              'metric_definition': {
                'id': 'don:core:dvrv-us-1:devo/787:metric_definition/1',
                'metric_type': 'time',
                'name': 'First response',
              },
              'stage': 'completed',
            }],
            'sla': {
              'display_id': 'sla-35',
              'id': 'don:core:dvrv-us-1:devo/787:sla/35',
              'name': 'Demo SLA with tickets',
              'status': 'published',
            },
            'sla_policy_id': 'don:core:dvrv-us-1:devo/787:sla/35:sla_policy/0',
            'stage': 'completed',
          },
          'stage': 'completed',
          'target_time': '2023-04-19T16:47:51.251Z',
        },
        'source_channel': 'chat',
        'stage': {
          'name': 'new',
          'ordinal': 1000,
        },
        'state': 'open',
        'status': 'open',
        'title': '',
      },
    },
    'id': 'don:integration:dvrv-us-1:devo/787:webhook/6BtxS8HQ:webhook_event/xcj1OqXXZG4',
    'timestamp': '2023-05-15T16:39:13.182596Z',
    'type': 'conversation_updated',
    'unique_key': 'ZG9uOmludGVncmF0aW9uOmR2cnYtdXMtMTpkZXZvLzc4NzpldmVudF9zb3VyY2UvN2VhM2NkZmEtODExMy00MWUzLWJjYjItNWM2NWQ3MTdjYmJi',
    'webhook_id': 'don:integration:dvrv-us-1:devo/787:webhook/6BtxS8HQ',
  },
  'context': {
    'dev_oid': 'don:identity:dvrv-us-1:devo/787',
    'automation_id': 'don:integration:dvrv-us-1:devo/787:automation/8563d233-4c37-49e9-a0a1-7a5953933868',
    'source_id': 'don:integration:dvrv-us-1:devo/787:automation/8563d233-4c37-49e9-a0a1-7a5953933868',
    'snap_in_id': 'don:integration:dvrv-us-1:devo/787:snap_in/0e3b41ce-9fea-4732-a256-d10109d366a3',
    'snap_in_version_id': 'don:integration:dvrv-us-1:devo/787:snap_in_package/3b70de87-4397-4136-b20a-cb0973bc5263:snap_in_version/73c3afb6-d10b-4f59-8210-8c2d947d8d10',
    'secrets': {
      'service_account_token': 'devrevtoken',
    },
  },
  'execution_metadata': {
    'request_id': '',
    'function_name': 'post_survey',
    'event_type': 'conversation_updated',
  },
  'input_data': {
    'global_values': {
      'survey_id': 'don:pulse:dvrv-us-1:devo/787:survey/1',
      'survey_resp_text': 'Thank you for sharing your feedback.',
      'survey_text': 'How satisfied were you with this chat?',
    },
    'event_sources': {
      'devrev-webhook': 'don:integration:dvrv-us-1:devo/787:event_source/7ea3cdfa-8113-41e3-bcb2-5c65d717cbbb',
    },
    'keyrings': null,
  },
};